# Generated by Django 6.0.6 on 2026-06-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Wallet', 'Wallet'), ('System', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='GCash reference number or payment reference number', max_length=100, null=True),
        ),
    ]
