# Generated by Django 6.0.6 on 2026-06-26 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('View', 'View'), ('Export', 'Export'), ('Payment', 'Payment'), ('Cancel', 'Cancel'), ('Status Change', 'Status Change'), ('Stock Movement', 'Stock Movement'), ('System', 'System')], max_length=50)),
                ('module', models.CharField(choices=[('Authentication', 'Authentication'), ('Dashboard', 'Dashboard'), ('Orders', 'Orders'), ('Payments', 'Payments'), ('Discounts', 'Discounts'), ('Product Management', 'Product Management'), ('Stock Management', 'Stock Management'), ('Ingredient Management', 'Ingredient Management'), ('Recipe Management', 'Recipe Management'), ('Reports', 'Reports'), ('CMS Announcements', 'CMS Announcements'), ('User Accounts', 'User Accounts'), ('System', 'System')], max_length=100)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('url_path', models.CharField(blank=True, max_length=255, null=True)),
                ('http_method', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
