# Generated by Django 6.0.6 on 2026-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audittrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Authentication', 'Authentication'), ('Dashboard', 'Dashboard'), ('Orders', 'Orders'), ('Payments', 'Payments'), ('Discounts', 'Discounts'), ('Product Management', 'Product Management'), ('Stock Management', 'Stock Management'), ('Product Availability', 'Product Availability'), ('Ingredient Management', 'Ingredient Management'), ('Recipe Management', 'Recipe Management'), ('Reports', 'Reports'), ('CMS Announcements', 'CMS Announcements'), ('User Accounts', 'User Accounts'), ('System', 'System')], max_length=100),
        ),
    ]
