# Generated by Django 6.0.6 on 2026-06-23 06:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_discount_amount_order_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Senior', 'Senior Citizen'), ('PWD', 'PWD'), ('Promo', 'Promo'), ('Manual', 'Manual Discount')], max_length=20)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount'), ('Buy 1 Take 1', 'Buy 1 Take 1')], default='Percentage', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Example: 20.00 means 20%', max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_id_card', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_quantity', models.PositiveIntegerField(default=1)),
                ('cardholder_name', models.CharField(blank=True, max_length=150, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_item_discounts', to=settings.AUTH_USER_MODEL)),
                ('discount_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_discounts', to='discounts.discountrule')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
    ]
