# Generated by Django 6.0.6 on 2026-06-23 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_quantity_product_image_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('Adjustment', 'Adjustment'), ('Return', 'Return')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('previous_quantity', models.PositiveIntegerField(default=0)),
                ('new_quantity', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, help_text='Example: Order #15, Restock Delivery, Manual Adjustment', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-movement_date'],
            },
        ),
    ]
