# Generated by Django 6.0.6 on 2026-06-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_category__name', 'name', 'size']},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product cost / puhunan per item', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Example: AMR-REG-0001', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Upgrade', 'Upgrade'), ('Mega', 'Mega'), ('Not Applicable', 'Not Applicable')], default='Not Applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
