# Generated by Django 6.0.6 on 2026-06-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_options_product_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('L', 'Liters'), ('pc', 'Pieces'), ('pack', 'Packs')], default='pc', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Current available ingredient quantity', max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, help_text='Minimum quantity before restock is recommended', max_digits=12)),
                ('safety_buffer_percent', models.DecimalField(decimal_places=2, default=10, help_text='Additional buffer percentage for weekly planning', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, default=0, help_text='Ingredient quantity needed to produce one unit of this product', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_recipes', to='inventory.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Recipe Item',
                'verbose_name_plural': 'Product Recipe Items',
                'ordering': ['product__name', 'ingredient__name'],
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
