# Generated by Django 6.0.6 on 2026-06-26 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredient_productrecipeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Example: Delivery Receipt #001, Manual Adjustment', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingredient Movement',
                'verbose_name_plural': 'Ingredient Movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
