# Generated by Django 6.0.6 on 2026-06-24 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shift_start', models.DateTimeField(auto_now_add=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_payouts', models.DecimalField(decimal_places=2, default=0, help_text='Manual cash deductions such as expenses or cash drops.', max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cash_counted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('over_short_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gcash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gcash_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_processed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('received_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_cashier_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_start'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Open')), fields=('cashier',), name='unique_open_shift_per_cashier')],
            },
        ),
    ]
