# Generated by Django 6.0.6 on 2026-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
