# Generated by Django 6.0.6 on 2026-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_sitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_page_images/'),
        ),
    ]
