# Generated by Django 6.0.6 on 2026-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ingredients_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
